### ISSUE TITLE
All torrents failing with "Unregistered Torrent"

### ISSUE THREAD

**Issue by XanderStrike** [Mechazawa/REDBetter-crawler#14]
When I re-download the torrent from RED, it works just fine. Unfortunately, this makes the system painfully hands on.

Here's a diff of the RED torrent and the one generated by this script (top is working):

```
xander@cryobank:~$ diff -a from_red.torrent from_pthbetter.torrent
18c18
< �|��K�8H(�jQؗ�
               T�3�~��Mq��
                          Ų�tr��I1��UU�q�7:privatei1e6:source3:REDee
\ No newline at end of file
---
> �|��K�8H(�jQؗ�
               T�3�~��Mq��
                          Ų�tr��I1��UU�q�7:privatei1eee
\ No newline at end of file
```

Is something wrong with my configuration? Is there a flag I can add to mktorrent that will fix this? Is it working for anyone else?

**Comment by SavageCore** [comment]
Probably found out by now but for anyone else. You have to compile mktorrent from source for -s (source) support.

Snippet of how I do it: https://gist.githubusercontent.com/SavageCore/224195787a2ad9bf6fe5e6065c1b2857/raw/2900757df5f9f37a5cdec80e931e5059a621b225/mktorrent.sh
