### ISSUE TITLE
No config file or folder

### ISSUE THREAD

**Issue by RhmBWT** [Mechazawa/REDBetter-crawler#25]
Following README.md

> alexander@archlabs ~ % ./redactedbetter 
>   File "./redactedbetter", line 87
>     print 'Please edit the configuration file: %s' % args.config
>                                                  ^
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print 'Please edit the configuration file: %s' % args.config)?

So after this there aren't any config file or folder generated.

**Comment by leninsaccountant** [comment]
did you find a solution to this?
