### ISSUE TITLE
Does this script still scrape in a disallowed manner?

### ISSUE THREAD

**Issue by smesseim** [Mechazawa/REDBetter-crawler#33]
The README states that this script breaks the Golden Rules. Is this still correct? If so, which of the interactions in this script are disallowed? Perhaps there could be a workaround (e.g. instead of scraping better.php, the user could download the better.php page and pass that as an input to this script). I can work on that if I know where the issue lies.

**Comment by Mechazawa** [comment]
nope it hasn't for quite a while https://github.com/Mechazawa/REDBetter-crawler/search?q=request_html&unscoped_q=request_html

it used to though.
