### ISSUE TITLE
Code borrowing

### ISSUE THREAD

**Issue by equals215** [Mechazawa/REDBetter-crawler#42]
Hi,
I'm currently working on a RED related project and I need to use the API of RED.
Can I use the redactedapi.py file in my project ?
I'll, of course, mention your repo in this file.

**Comment by Mechazawa** [comment]
I'm not the original author, I remember getting it from somewhere else. So as far as I'm concerned feel free.

**Comment by equals215** [comment]
Thanks for your answer !
